apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tfl-app.fullname" . }}
  labels:
    {{- include "tfl-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tfl-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "tfl-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
